### ISSUE TITLE
Panic when starting stanza using a service account without Log Writer role (Google Output)

### ISSUE THREAD

**Issue by jsirianni** [observIQ/stanza#264]
**Describe the bug**

Stanza panics if the service account does not have Logs Writer.

**To Reproduce**
1. start stanza with a working configuration, send logs to Google
2. remove the service accounts "Logs Writer" role
3. wait for stanza error log to indicate that there is a permission issue
4. stop stanza
5. start stanza (panic occurs)

**Expected behavior**

Stanza should start fine, and continue to log permission errors.

**Screenshots**
```
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x13346ed]

goroutine 1 [running]:
github.com/observiq/stanza/operator/builtin/input/tcp.(*TCPInput).Stop(0xc00057b040, 0xc00000ecff, 0x0)
	/Users/jsirianni/git/go/src/github.com/observiq/stanza/operator/builtin/input/tcp/tcp.go:229 +0x2d
github.com/observiq/stanza/pipeline.(*DirectedPipeline).Stop(0xc00000ea78, 0x0, 0xc003911668)
	/Users/jsirianni/git/go/src/github.com/observiq/stanza/pipeline/directed.go:42 +0x13f
github.com/observiq/stanza/agent.(*LogAgent).Stop.func1()
	/Users/jsirianni/git/go/src/github.com/observiq/stanza/agent/agent.go:36 +0x45
sync.(*Once).doSlow(0xc0004903ec, 0xc0004a1ab0)
	/usr/local/Cellar/go/1.16.2/libexec/src/sync/once.go:68 +0xec
sync.(*Once).Do(...)
	/usr/local/Cellar/go/1.16.2/libexec/src/sync/once.go:59
github.com/observiq/stanza/agent.(*LogAgent).Stop(0xc0004903c0, 0x0, 0x0)
	/Users/jsirianni/git/go/src/github.com/observiq/stanza/agent/agent.go:35 +0x7d
main.(*AgentService).Stop(0xc0005ace10, 0x214c348, 0xc0005fb3b0, 0x7, 0xc0034bfa68)
	/Users/jsirianni/git/go/src/github.com/observiq/stanza/cmd/stanza/service.go:36 +0xbd
github.com/kardianos/service.(*systemd).Run(0xc0005fb3b0, 0xc000490480, 0xc000134090)
	/Users/jsirianni/git/go/pkg/mod/github.com/kardianos/service@v1.2.0/service_systemd_linux.go:229 +0xe9
main.runRoot(0xc000138c80, 0xc0000b7700, 0x0, 0x4, 0xc000134090)
	/Users/jsirianni/git/go/src/github.com/observiq/stanza/cmd/stanza/root.go:111 +0x453
main.NewRootCmd.func1(0xc000138c80, 0xc0000b7700, 0x0, 0x4)
	/Users/jsirianni/git/go/src/github.com/observiq/stanza/cmd/stanza/root.go:47 +0x52
github.com/spf13/cobra.(*Command).execute(0xc000138c80, 0xc000088060, 0x4, 0x4, 0xc000138c80, 0xc000088060)
	/Users/jsirianni/git/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:856 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0xc000138c80, 0x0, 0x2e27998, 0xc00008a058)
	/Users/jsirianni/git/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/jsirianni/git/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
main.main()
	/Users/jsirianni/git/go/src/github.com/observiq/stanza/cmd/stanza/main.go:9 +0x2b
```

**Environment:**
 - OS: Ubuntu 18.04 LTS
 - Stanza Version: v0.13.16

**Comment by jsirianni** [comment]
Looking into this further, it seems to happen when

1. There are entires buffered in the database
2. Stanza starts, fails to init Google output because test connection fails
3. Input operators are told to stop because an operator (google) failed. This causes the panic. 

Not sure why not.

**Comment by jsirianni** [comment]
Resolved here https://github.com/observIQ/stanza/pull/331

This can happen if an input operator tries to close something (such as a connection) when it failed to start, causing the panic. Unfortunately I forgot to post the config used in this specific example. I do not believe this is a Google Output issue.
